name: Build Flutter Windows App

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.5'
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop
    
    - name: Flutter Clean
      run: flutter clean
    
    - name: Flutter Pub Get
      run: flutter pub get
    
    - name: Build Release
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
        flutter build windows --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: build/windows/x64/runner/Release/
